namespace: payload-cms
resources:
  - ../../package
  - sealed-auth-secret.yaml
  - env-sealed-secret.yaml
labels:
  - pairs:
      env: production
      cluster: hcloud
    includeSelectors: true
    includeTemplates: true
patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: payload-cms
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`payload-cms.netsam.dev`)"
      - op: replace
        path: /spec/routes/1/match
        value: "Host(`payload-cms.netsam.dev`) && Path(`/admin`)"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: payload-cms
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "ghcr.io/andrewthomaslee/payload-cms/site/hcloud:latest"
