{
  "apiVersion": "bitnami.com/v1alpha1",
  "kind": "SealedSecret",
  "metadata": {
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    },
    "name": "basic-auth-secret"
  },
  "spec": {
    "encryptedData": {
      "auth": "AgAHBV1DMTcB1i7rvAF5yjdegIauRq6FxjuXcdsdK3OGjY6H1qkaO1wv0j3LmYo/z26ZHlV4s2Q+Aj4Ocp/mG1ZP2XajqgqOb8gfHSXIAbzdoRGhGgjLARuoqh0ZoQ9VqxjMbtZI/hGl3RaQH25Pf0a9+gvb1PAYN60jgRGQlocwMSl/ny4kuVavNwGocXywXhpkYXMJvWddkZQ3KVKGLohXfpThGtw3vnddXfdYMLOxDuttLQFmuLJ6RZk6Aa4GhIVSz5LIeVCxSgZiIGLYB9DvLdQiNTQusoKVToarQjtBpajXU4N/a0Am0785waC6a5eU8YFjM9ltHgjDAGyA7flKFJvaVjuoKIVB0eFesUHATMFISbsngmpNvS1kMHHB69XvcHO36q1Ywg3Xgeso1/zShuNJr/7f61haDoPnrR4zA/Bv9LyqypPkR63VpoTmxpxLeeMFxfUFXZm4Gkqdwv3Slu+d0LsxfyjBWwKCdiYJ9gvqS5u30DneRjkmqQLcjIGA/p3fwmOgXfPhqSQC3KWWKFOgxwN1OrikDY/wh/mvjJG/AhbB+luC5xKZpTLv5rkPLmNtwgM10MjUiVgh9/R8w9VbFJdiovKNTBW0na90f8vReJkXCaoWidnPcYjVucodhd2RbYtOxgHfKwMay3z0i0d/NvsOJCa9Au1S5KQ9IMHh7i+YD56swsXr2uz1T2oDqTMHtkbW6Refr/PXpmERAu5E7CCbumNDu7GsJ/rZ6+UEL9Jrj4Rag/eu"
    },
    "template": {
      "metadata": {
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        },
        "name": "basic-auth-secret"
      }
    }
  }
}
