{
  "apiVersion": "bitnami.com/v1alpha1",
  "kind": "SealedSecret",
  "metadata": {
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    },
    "name": "basic-auth-secret"
  },
  "spec": {
    "encryptedData": {
      "auth": "AgBGjyV7/IHTcOtumwnl6zAehgaGZ+kx46Bqy0yuqnWViPvXF4k0hMi/220x3PW67Yklm66mCXOe6QMXE7jTl9TmlFE4CLrlZ0xAQIhC6UQtLRErQOUEqyrUv76ZPVWa1j9khCEF8gqoblO4DkzZ54HLi1U22T37seN+z/6G61A6Ngs8aN3qX0x/oP//TEi8rz07P3a+VJPd1f0DzrZiy87d8r2tpxKK9BcbLBU71wkZg7+oeTieuFUFR+wYZeJtkXWulfxF8yQGiUhqLCdQ/miY7ARoATFlDnKi99H9AMnI1eDkqKPpf512po0PQT64IuyB79+kjOxq0tjHUOKeQu105UPaGsRAZyMHj6eYQfevXxQ9d9YHTaF6QgJFTrymHcB39anGOhZqk33jaUAQntMgyQleSZaNSdg95NS0tifgqU5dg32f9dnyXxO1k9/6WSJ2CFy/sD5eWvDpemAKppOAhbgnA1bjHiNdaviu4ucoXr8rdgOoR7k9v41wQmI18bQlHSz0OHyJP3M9BJZ3+LpAl8s3iNrGWZxDCY0ZbtiTrVmpBpkIeK52rw44c7DEPou4NclwaMnN0FTZEUTx5RcPveVroayWcAQbKdNENku5fq0Czi6e3DT+NUPrx80mtfSFWIPDkV+9kMh6Kmo74D7ORGLa3yWvQyTGUCRuDLM5prlIvnCnMQl5wCSOh+v7nMox5nWpI7xhmVHt4KjPmhM6Ma+xNLVDNXYIiTD8doDtZQwC/5uEJsm7L0vi"
    },
    "template": {
      "metadata": {
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        },
        "name": "basic-auth-secret"
      }
    }
  }
}
