services:
  payload-cms:
    image: ghcr.io/andrewthomaslee/payload-cms/site:latest
    pull_policy: always
    container_name: payload-cms
    network_mode: host
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    volumes:
      - payload-cms-media:/app/public/media
      - payload-cms-cache:/app/.next/cache

volumes:
  payload-cms-media:
  payload-cms-cache:
