apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - payload-cms-ingress.yaml
  - payload-cms-namespace.yaml
  - payload-cms-persistentvolumeclaim.yaml
  - payload-cms-service.yaml
  - payload-cms-statefulset.yaml
