apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    io.kompose.service: payload-cms
  name: payload-cms
  namespace: payload-cms
spec:
  ingressClassName: traefik
  rules:
    - host: andrewlee.fun
      http:
        paths:
          - backend:
              service:
                name: payload-cms
                port:
                  number: 3000
            path: /
            pathType: Prefix
