apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: payload-cms-media
  name: payload-cms-media
  namespace: payload-cms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
