apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: payload-cms
  name: payload-cms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
