apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: payload-cms
  name: payload-cms
  namespace: payload-cms
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
      appProtocol: http
  selector:
    io.kompose.service: payload-cms
  type: ClusterIP
