apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: payload-cms-chart
  namespace: payload-cms-dev
spec:
  interval: 5m
  url: oci://ghcr.io/andrewthomaslee/payload-cms/chart
  ref:
    semver: '>=0.1.0'
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  # Enable when the chart package is private:
  # secretRef:
  #   name: ghcr-pull-secret
