{
  "apiVersion": "bitnami.com/v1alpha1",
  "kind": "SealedSecret",
  "metadata": {
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    },
    "name": "basic-auth-secret"
  },
  "spec": {
    "encryptedData": {
      "auth": "AgBgTgrq2kQ0yrznkJDJRo6ZqbDftBw824fM4TqYvIV7U/n1XeeioJbrl/hT8hYeb1Hwmwe+SC+rxsjaAQxOjaqElfVDjYi2iMZLnz1Kp1u6QDGtvBB16OuWN21LJdLybid4EACFPQjbCOYJJul5IOMpSlN/Vz7sjL9SLPvnhAa2sKpk/sapj8UwEH4dt+5fkBVKNERgPFBf7unQ5wqDLUn/viiKt1SKn76yb3s4+ijJvwH4qYUO/dZNXC+gzJmcgN8xSCGeqqAtFWRGaTKzBAtscfNMCVYBqbQS9jW2MGj5woRaHshCZMCNpW/te4KgMKmu0lnl2mTUkdsnH7dNg+QI9uNBkW8OwpFcAI3vEDDeqtOQ4NbpRKfSnkjzth/8oMGA9fDXPHeRx51CpU7ofjTsB1C4Yw/XLPiRSqKypZm2MoedTgeYz8B9h3sqmslTmKXsX4l4rBIALA80gyJJNSvqffqRPgoOo9UPTMZ8+PdrwdzxGPAlyMZYejJOzvwAYebP+HZKKV+VRj8+c7tVOvhqAk8JyBYwGEVi6XeU5S7Zr9iP9J4neUNgbYI2sgdfn9jpdIdJjHguxoTrPHrTexbdPritCZrlGvjyZPVrDmFMIa/WSplS2iVLlki2fFd0igYy2hVLN50BrNzHDuiQ/6l4BMi+Pxf09soBA7C4grIXQhOLoVSlZS3h+vOv9jTf+OY3YJb0oFbgvoEf/66aItOI4QrG9GFKrDc4d/R5o9RFIoB0A5o/9WUr4JER"
    },
    "template": {
      "metadata": {
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        },
        "name": "basic-auth-secret"
      }
    }
  }
}
