{
  "apiVersion": "bitnami.com/v1alpha1",
  "kind": "SealedSecret",
  "metadata": {
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    },
    "name": "basic-auth-secret"
  },
  "spec": {
    "encryptedData": {
      "auth": "AgAvYbtY74CyltQG89YlrEZ8Ne5jay/0t/pz1ogjPTMrai4NAgf05bbolHFUarkAShZcNanzo4zTluTLiOo0yqjJJIRnL57hG8vuKTNhH765UyHAIKIgtpJhJLCcyQ9gcpXZ/WdIWcFRYjnINB+eGHLWfqVYjHDFMIKDayEDTDvmHdnZFZz1LjT/GuXmciwsUtVlX9B1/7C2S4q5uiXR+bc5yjjUBsV+yNDiULpKa/f7bQ+EjXMVhAvU0CBMUGKe4OiBVGTnG+r3qJHUf7FZsGPnUi2gwbsOQC9KnnCmAYcUqcHeugZYOp5VEnqAHozCVP47aa4pyjcU7Uq6k6r/1+qjJfX/Pgqrz9iuVwQvY2H9opF6z+mKUj5sqGvOD2yc8YlGyEdq4UEbSJNaV4CxBEBG87725XDXL6lyRQijkJHjt631xA4xV8pE1r/UjO0HkX9M9AtgkVP0jYh/GdWNpXWPwFdkN/Nnez5cvz+4yTfhTVkImmtoA1g5ttt/rCIUDF9l3Ub0aM2XhoSGCMYbdjNBSo5VaMKdZSokx9O80tYqi2fPlw5Q0Cv9PpVp5SMR7PZ9ulisLRWMKMA6k/+Y/eeq9fQ1SaZYeDFGpKcHYIB9UzXysVydPLNe8NJqmuwY+ho++NaqOTftFYhOMzFS5XaaGAAoCCEHMwq+J5FMd/B0+UpWbJUos/RGuY6orjdwSOTRmHz2mEPt1+gpISBZyBm31twwXwzmWYu3ys7E2B3c1TlcMi9IbwKNcAIg"
    },
    "template": {
      "metadata": {
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        },
        "name": "basic-auth-secret"
      }
    }
  }
}
