name: Reusable Build Site
on: workflow_call
jobs:
  build-site:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: true

      - uses: NX1X/cloudflare-warp-action@v1
        name: Install WARP
        with:
          organization: ${{ secrets.CF_WARP_ORG }}
          auth-client-id: ${{ secrets.CF_WARP_CLIENT_ID }}
          auth-client-secret: ${{ secrets.CF_WARP_CLIENT_SECRET }}

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Build Site
        run: nix build --show-trace
