name: Reusable Flakehub
on: workflow_call
jobs:
  push-to-cache:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: private
          name: andrewthomaslee/payload-cms
          include-output-paths: true
          rolling: true
          rolling-minor: 1
