name: build-hcloud

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: hcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get Commit Count
        id: vars
        run: echo "commit_count=$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6.1.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/payload-cms/site/hcloud
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.vars.outputs.commit_count }}
          flavor: latest=auto

      - name: Install WARP
        uses: Boostport/setup-cloudflare-warp@v1
        with:
          organization: ${{ vars.CF_WARP_ORG }}
          auth_client_id: ${{ secrets.CF_WARP_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CF_WARP_CLIENT_SECRET }}
          configure_docker_dns: true

      - name: Test Connection
        run: curl --retry 3 --retry-delay 5 --max-time 10 whoami.whoami.svc.hcloud.cluster

      - name: Discover Host DNS Namespace
        id: dns-discovery
        run: |
          NAMESERVER=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n 1)
          echo "nameserver=$NAMESERVER" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0
        with:
          driver-opts: |
            network=host
          buildkitd-flags: |
            --allow-insecure-entitlement network.host
          buildkitd-config-inline: |
            [worker.oci]
              dns-search = ["hcloud.cluster"]
              dns-nameservers = ["${{ steps.dns-discovery.outputs.nameserver }}"]

      - name: Build and push
        id: build
        uses: docker/build-push-action@v7.2.0
        env:
          BUILD_ENV_FILE: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
            CRON_SECRET=${{ secrets.CRON_SECRET }}
            PREVIEW_SECRET=${{ secrets.PREVIEW_SECRET }}
            NEXT_PUBLIC_SERVER_URL=${{ vars.NEXT_PUBLIC_SERVER_URL }}
        with:
          network: host
          allow: network.host
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secret-envs: env-file=BUILD_ENV_FILE
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/payload-cms/site/hcloud:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/payload-cms/site/hcloud:buildcache,mode=max

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.2

      - name: Sign the images with GitHub OIDC Token
        env:
          IMAGE_DIGEST: ${{ steps.build.outputs.digest }}
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/payload-cms/site/hcloud
        run: |
          cosign sign --yes "${IMAGE_NAME}@${IMAGE_DIGEST}"
