name: ci

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Nix Flake Check
        run: nix flake check --show-trace
