name: Release

permissions:
  id-token: write
  contents: write
  packages: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  pre-flight:
    uses: ./.github/workflows/_flake-check.yml

  shell:
    needs: pre-flight
    uses: ./.github/workflows/_build-shell.yml

  flakehub:
    needs: shell
    uses: ./.github/workflows/_flakehub.yml

  tag:
    needs: flakehub
    uses: ./.github/workflows/_release.yml
    secrets: inherit

  push:
    needs: tag
    uses: ./.github/workflows/_oci.yml
    with:
      tag: ${{ needs.tag.outputs.tag }}
    secrets: inherit
